apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-aws
  template:
    metadata:
      labels:
        app: nginx-aws
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: index
        configMap:
          name: nginx-index
