---
- name: Configure AWS App and Azure VM and Tools
  hosts: all
  become: yes
  vars:
    aws_index_src: "../k8s/index-aws.html"
    azure_index_src: "../k8s/index-azure.html"

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Configure App (AWS) server
  hosts: aws
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy AWS index page
      copy:
        src: ../k8s/index-aws.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

- name: Configure Azure server
  hosts: azure
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy Azure index page
      copy:
        src: ../k8s/index-azure.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

- name: Install Jenkins on Tools server
  hosts: tools
  become: yes
  tasks:
    - name: Install Java (OpenJDK)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins apt repo key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repo
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt and install Jenkins
      apt:
        update_cache: yes
        name: jenkins
        state: present

    - name: Ensure Jenkins is running
      systemd:
        name: jenkins
        state: started
        enabled: yes
