---
- name: Configure All Servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- name: Configure App (AWS) Server
  hosts: aws
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Copy AWS index page
      copy:
        src: ../k8s/index-aws.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

- name: Configure Tools Server
  hosts: tools
  become: yes
  tasks:
    - name: Ensure Java is installed (required for Jenkins and builds)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Ensure Jenkins is running
      systemd:
        name: jenkins
        state: started
        enabled: yes
